### ISSUE TITLE
V2: Refactors vars to vars file

### ISSUE THREAD

**Issue by rhysmeister** [rhysmeister/AutomatingMongoDBWithAnsible#74]
Many plays in a few Playbook have variables defined multiple timres. These could be placed into vars/main.yml. For example...

```yaml
vars:
  required_packages:
    - "yum-plugin-versionlock"
  current_mongodb_version: "4.2"
  target_mongodb_version: "4.0"
```
